In [5]:
import os
from pathlib import Path
import pandas as pd

# 相対パスの指定（1つ上の層の data フォルダを参照）
file_path = Path("../data/地域幸福度_市区町村別データ_2022-2026.xlsx")

if not file_path.exists():
    print(
        f"❌ ファイルが見つかりません。絶対パス:\n   {file_path.resolve()}"
    )
    print(f"   現在の実行位置: {os.getcwd()}")
else:
    print("✅ ファイルを確認しました。")

    excel_file = pd.ExcelFile(file_path)
    sheet_names = excel_file.sheet_names
    print("シート一覧:", sheet_names)

    # 2個目のシート（インデックス: 1）
    if len(sheet_names) > 1:
        sheet2_name = sheet_names[1]
        df_sheet2 = pd.read_excel(file_path, sheet_name=1)
        print(f"\n=== 📄 2個目のシート: 【{sheet2_name}】 ===")
        print(f"・サイズ (行, 列): {df_sheet2.shape}")
        display(df_sheet2.head())
    else:
        print("\n⚠️ 2個目のシートが存在しません。")

    # 3個目のシート（インデックス: 2）
    if len(sheet_names) > 2:
        sheet3_name = sheet_names[2]
        df_sheet3 = pd.read_excel(file_path, sheet_name=2)
        print(f"\n=== 📄 3個目のシート: 【{sheet3_name}】 ===")
        print(f"・サイズ (行, 列): {df_sheet3.shape}")
        display(df_sheet3.head())
    else:
        print("\n⚠️ 3個目のシートが存在しません。")

✅ ファイルを確認しました。
シート一覧: ['説明', '主観データ', '客観データ']

=== 📄 2個目のシート: 【主観データ】 ===
・サイズ (行, 列): (95968, 38)

,年度,都道府県,市区町村,地域ID,区分,年代,性別,回答者数,主観_医療・福祉,主観_買物・飲食,...,主観_文化・芸術,主観_教育機会の豊かさ,主観_雇用・所得,主観_事業創造,幸福度,生活満足度,5年後の幸福度,町内の幸福度,周りも楽しい,町内の幸福度回答者数
0,2026,北海道,札幌市全域,2,全体,NaN,NaN,1062,60.981,58.813,...,53.387,57.866,57.322,56.299,6.471,6.959,6.277,6.331,3.208,785.0
1,2026,北海道,札幌市全域,2,年代別,10代,NaN,2,53.726,74.741,...,65.492,80.840,87.065,90.275,6.500,7.500,8.000,7.000,4.000,2.0
2,2026,北海道,札幌市全域,2,年代別,20代,NaN,15,82.845,78.811,...,76.710,86.806,90.320,84.866,6.467,6.467,7.133,6.000,3.800,10.0
3,2026,北海道,札幌市全域,2,年代別,30代,NaN,60,62.053,59.477,...,52.645,59.961,65.810,71.341,6.467,6.800,6.650,6.468,3.367,47.0
4,2026,北海道,札幌市全域,2,年代別,40代,NaN,170,54.159,62.216,...,39.471,47.154,51.149,52.725,5.747,6.582,5.582,6.172,3.082,116.0

=== 📄 3個目のシート: 【客観データ】 ===
・サイズ (行, 列): (8981, 28)

,年度,都道府県,市区町村,地域ID,客観_医療・福祉,客観_買物・飲食,客観_住宅環境,客観_移動・交通,客観_遊び・娯楽,客観_子育て,...,客観_環境共生,客観_自然災害,客観_地域とのつながり,客観_多様性と寛容性,客観_自己効力感,客観_健康状態,客観_文化・芸術,客観_教育機会の豊かさ,客観_雇用・所得,客観_事業創造
0,2026,北海道,札幌市全域,2,43.224,51.957,46.673,57.031,47.599,48.08,...,56.144,53.784,48.755,52.79,56.104,48.05,53.715,50.104,41.907,62.491
1,2026,北海道,札幌市中央区,3,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026,北海道,札幌市北区,4,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026,北海道,札幌市東区,5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026,北海道,札幌市白石区,6,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# 2個目のシート（主観データ）の全列名
print(
    f"=== 📄 2個目のシート【主観データ】の列一覧 (全 {len(df_sheet2.columns)} 列) ==="
)
print(list(df_sheet2.columns))

print("\n" + "=" * 60 + "\n")

# 3個目のシート（客観データ）の全列名
print(
    f"=== 📄 3個目のシート【客観データ】の列一覧 (全 {len(df_sheet3.columns)} 列) ==="
)
print(list(df_sheet3.columns))

=== 📄 2個目のシート【主観データ】の列一覧 (全 38 列) ===
['年度', '都道府県', '市区町村', '地域ID', '区分', '年代', '性別', '回答者数', '主観_医療・福祉', '主観_買物・飲食', '主観_住宅環境', '主観_移動・交通', '主観_遊び・娯楽', '主観_子育て', '主観_初等・中等教育', '主観_地域行政', '主観_デジタル生活', '主観_公共空間', '主観_都市景観', '主観_事故・犯罪', '主観_自然景観', '主観_自然の恵み', '主観_環境共生', '主観_自然災害', '主観_地域とのつながり', '主観_多様性と寛容性', '主観_自己効力感', '主観_健康状態', '主観_文化・芸術', '主観_教育機会の豊かさ', '主観_雇用・所得', '主観_事業創造', '幸福度', '生活満足度', '5年後の幸福度', '町内の幸福度', '周りも楽しい', '町内の幸福度回答者数']

============================================================

=== 📄 3個目のシート【客観データ】の列一覧 (全 28 列) ===
['年度', '都道府県', '市区町村', '地域ID', '客観_医療・福祉', '客観_買物・飲食', '客観_住宅環境', '客観_移動・交通', '客観_遊び・娯楽', '客観_子育て', '客観_初等・中等教育', '客観_地域行政', '客観_デジタル生活', '客観_公共空間', '客観_都市景観', '客観_事故・犯罪', '客観_自然景観', '客観_自然の恵み', '客観_環境共生', '客観_自然災害', '客観_地域とのつながり', '客観_多様性と寛容性', '客観_自己効力感', '客観_健康状態', '客観_文化・芸術', '客観_教育機会の豊かさ', '客観_雇用・所得', '客観_事業創造']

In [9]:
# 主観データの「区分」内訳を確認
print("【主観データの区分一覧】")
print(df_sheet2["区分"].value_counts())

【主観データの区分一覧】
区分
年代×性別    48461
年代別      27969
性別別      10557
全体        8981
Name: count, dtype: int64

In [11]:
# 区分ごとにグループ化して欠損状況を集計
for kbn, group in df_sheet2.groupby("区分"):
    print(f"\n==========================================")
    print(f"■ 区分: 【{kbn}】 (総行数: {len(group)} 行)")
    print(f"==========================================")

    # 欠損がある列のみ抽出
    null_counts = group.isnull().sum()
    null_rates = (group.isnull().mean() * 100).round(2)

    df_kbn_nan = pd.DataFrame({"欠損数": null_counts, "欠損率(%)": null_rates})
    df_kbn_nan_filtered = df_kbn_nan[df_kbn_nan["欠損数"] > 0]

    if df_kbn_nan_filtered.empty:
        print("  ✅ 欠損値（NaN）はありません。")
    else:
        display(df_kbn_nan_filtered)

==========================================
■ 区分: 【全体】 (総行数: 8981 行)
==========================================

              欠損数  欠損率(%)
年代           8981  100.00
性別           8981  100.00
主観_医療・福祉     4241   47.22
主観_買物・飲食     4241   47.22
主観_住宅環境      4241   47.22
主観_移動・交通     4241   47.22
主観_遊び・娯楽     5574   62.06
主観_子育て       5574   62.06
主観_初等・中等教育   5574   62.06
主観_地域行政      4241   47.22
主観_デジタル生活    5574   62.06
主観_公共空間      4241   47.22
主観_都市景観      4241   47.22
主観_事故・犯罪     4241   47.22
主観_自然景観      4241   47.22
主観_自然の恵み     5574   62.06
主観_環境共生      5574   62.06
主観_自然災害      5574   62.06
主観_地域とのつながり  4241   47.22
主観_多様性と寛容性   4241   47.22
主観_自己効力感     4241   47.22
主観_健康状態      4241   47.22
主観_文化・芸術     4241   47.22
主観_教育機会の豊かさ  5574   62.06
主観_雇用・所得     5574   62.06
主観_事業創造      4241   47.22
幸福度          4241   47.22
生活満足度        4241   47.22
5年後の幸福度      5574   62.06
町内の幸福度       4243   47.24
周りも楽しい       4241   47.22
町内の幸福度回答者数   4241   47.22

==========================================
■ 区分: 【年代×性別】 (総行数: 48461 行)
==========================================

               欠損数  欠損率(%)
主観_遊び・娯楽     10096   20.83
主観_子育て       10096   20.83
主観_初等・中等教育   10096   20.83
主観_デジタル生活    10096   20.83
主観_自然の恵み     10096   20.83
主観_環境共生      10096   20.83
主観_自然災害      10096   20.83
主観_教育機会の豊かさ  10096   20.83
主観_雇用・所得     10096   20.83
5年後の幸福度      10096   20.83
町内の幸福度        1600    3.30

==========================================
■ 区分: 【年代別】 (総行数: 27969 行)
==========================================

               欠損数  欠損率(%)
性別           27969  100.00
主観_遊び・娯楽      6401   22.89
主観_子育て        6401   22.89
主観_初等・中等教育    6401   22.89
主観_デジタル生活     6401   22.89
主観_自然の恵み      6401   22.89
主観_環境共生       6401   22.89
主観_自然災害       6401   22.89
主観_教育機会の豊かさ   6401   22.89
主観_雇用・所得      6401   22.89
5年後の幸福度       6401   22.89
町内の幸福度         713    2.55

==========================================
■ 区分: 【性別別】 (総行数: 10557 行)
==========================================

               欠損数  欠損率(%)
年代           10557  100.00
主観_遊び・娯楽      2528   23.95
主観_子育て        2528   23.95
主観_初等・中等教育    2528   23.95
主観_デジタル生活     2528   23.95
主観_自然の恵み      2528   23.95
主観_環境共生       2528   23.95
主観_自然災害       2528   23.95
主観_教育機会の豊かさ   2528   23.95
主観_雇用・所得      2528   23.95
5年後の幸福度       2528   23.95
町内の幸福度         368    3.49

In [17]:
for kbn, group in df_sheet2.groupby("区分"):
    print(f"\n===== {kbn} =====")
    
    null_counts = group.isnull().sum()
    display(null_counts.to_frame("欠損数"))

===== 全体 =====

              欠損数
年度              0
都道府県            0
市区町村            0
地域ID            0
区分              0
年代           8981
性別           8981
回答者数            0
主観_医療・福祉     4241
主観_買物・飲食     4241
主観_住宅環境      4241
主観_移動・交通     4241
主観_遊び・娯楽     5574
主観_子育て       5574
主観_初等・中等教育   5574
主観_地域行政      4241
主観_デジタル生活    5574
主観_公共空間      4241
主観_都市景観      4241
主観_事故・犯罪     4241
主観_自然景観      4241
主観_自然の恵み     5574
主観_環境共生      5574
主観_自然災害      5574
主観_地域とのつながり  4241
主観_多様性と寛容性   4241
主観_自己効力感     4241
主観_健康状態      4241
主観_文化・芸術     4241
主観_教育機会の豊かさ  5574
主観_雇用・所得     5574
主観_事業創造      4241
幸福度          4241
生活満足度        4241
5年後の幸福度      5574
町内の幸福度       4243
周りも楽しい       4241
町内の幸福度回答者数   4241

===== 年代×性別 =====

               欠損数
年度               0
都道府県             0
市区町村             0
地域ID             0
区分               0
年代               0
性別               0
回答者数             0
主観_医療・福祉         0
主観_買物・飲食         0
主観_住宅環境          0
主観_移動・交通         0
主観_遊び・娯楽     10096
主観_子育て       10096
主観_初等・中等教育   10096
主観_地域行政          0
主観_デジタル生活    10096
主観_公共空間          0
主観_都市景観          0
主観_事故・犯罪         0
主観_自然景観          0
主観_自然の恵み     10096
主観_環境共生      10096
主観_自然災害      10096
主観_地域とのつながり      0
主観_多様性と寛容性       0
主観_自己効力感         0
主観_健康状態          0
主観_文化・芸術         0
主観_教育機会の豊かさ  10096
主観_雇用・所得     10096
主観_事業創造          0
幸福度              0
生活満足度            0
5年後の幸福度      10096
町内の幸福度        1600
周りも楽しい           0
町内の幸福度回答者数       0

===== 年代別 =====

               欠損数
年度               0
都道府県             0
市区町村             0
地域ID             0
区分               0
年代               0
性別           27969
回答者数             0
主観_医療・福祉         0
主観_買物・飲食         0
主観_住宅環境          0
主観_移動・交通         0
主観_遊び・娯楽      6401
主観_子育て        6401
主観_初等・中等教育    6401
主観_地域行政          0
主観_デジタル生活     6401
主観_公共空間          0
主観_都市景観          0
主観_事故・犯罪         0
主観_自然景観          0
主観_自然の恵み      6401
主観_環境共生       6401
主観_自然災害       6401
主観_地域とのつながり      0
主観_多様性と寛容性       0
主観_自己効力感         0
主観_健康状態          0
主観_文化・芸術         0
主観_教育機会の豊かさ   6401
主観_雇用・所得      6401
主観_事業創造          0
幸福度              0
生活満足度            0
5年後の幸福度       6401
町内の幸福度         713
周りも楽しい           0
町内の幸福度回答者数       0

===== 性別別 =====

               欠損数
年度               0
都道府県             0
市区町村             0
地域ID             0
区分               0
年代           10557
性別               0
回答者数             0
主観_医療・福祉         0
主観_買物・飲食         0
主観_住宅環境          0
主観_移動・交通         0
主観_遊び・娯楽      2528
主観_子育て        2528
主観_初等・中等教育    2528
主観_地域行政          0
主観_デジタル生活     2528
主観_公共空間          0
主観_都市景観          0
主観_事故・犯罪         0
主観_自然景観          0
主観_自然の恵み      2528
主観_環境共生       2528
主観_自然災害       2528
主観_地域とのつながり      0
主観_多様性と寛容性       0
主観_自己効力感         0
主観_健康状態          0
主観_文化・芸術         0
主観_教育機会の豊かさ   2528
主観_雇用・所得      2528
主観_事業創造          0
幸福度              0
生活満足度            0
5年後の幸福度       2528
町内の幸福度         368
周りも楽しい           0
町内の幸福度回答者数       0

In [13]:
#％が違う原因を調べる、年度によってない質問があるのか？
# 区分「全体」のデータのみ抽出
df_all = df_sheet2[df_sheet2["区分"] == "全体"].copy()

# 欠損数が異なる代表的な2つの列を設定
col_a = "幸福度"  # 欠損数 4,241件（欠損率 47.22%）
col_b = "主観_デジタル生活"  # 欠損数 5,574件（欠損率 62.06%）

# 1. 年度ごとに「数値が入っている（非欠損の）行数」を比較
check_by_year = df_all.groupby("年度")[[col_a, col_b]].count()
check_by_year.columns = [f"{col_a}（データ数）", f"{col_b}（データ数）"]
check_by_year["差分（件数）"] = (
    check_by_year[f"{col_a}（データ数）"]
    - check_by_year[f"{col_b}（データ数）"]
)

print("=== 📄 1. 年度ごとの指標別・データ存在件数 ===")
display(check_by_year)

# 2. 「幸福度」はあるのに「主観_デジタル生活」が欠損している1,333件の年度内訳
diff_rows = df_all[df_all[col_a].notnull() & df_all[col_b].isnull()]
print(
    f"\n=== 📄 2. 『{col_a}』はあり『{col_b}』が無い行（計 {len(diff_rows)} 件）の年度別内訳 ==="
)
print(diff_rows["年度"].value_counts().sort_index())

=== 📄 1. 年度ごとの指標別・データ存在件数 ===

      幸福度（データ数）  主観_デジタル生活（データ数）  差分（件数）
年度
2022       1333                0    1333
2023       1094             1094       0
2024        855              855       0
2025        701              701       0
2026        757              757       0

=== 📄 2. 『幸福度』はあり『主観_デジタル生活』が無い行（計 1333 件）の年度別内訳 ===
年度
2022    1333
Name: count, dtype: int64

In [14]:
# 「全体」データのみ
df_all = df_sheet2[df_sheet2["区分"] == "全体"].copy()

# 分析対象となる指標列
indicator_cols = [
    c for c in df_all.columns
    if c.startswith("主観_") or c in ["幸福度", "生活満足度", "5年後の幸福度"]
]

# 年度ごとの欠損率
missing_by_year = (
    df_all.groupby("年度")[indicator_cols]
    .apply(lambda x: x.isna().mean() * 100)
    .round(2)
)

display(missing_by_year)

,主観_医療・福祉,主観_買物・飲食,主観_住宅環境,主観_移動・交通,主観_遊び・娯楽,主観_子育て,主観_初等・中等教育,主観_地域行政,主観_デジタル生活,主観_公共空間,...,主観_多様性と寛容性,主観_自己効力感,主観_健康状態,主観_文化・芸術,主観_教育機会の豊かさ,主観_雇用・所得,主観_事業創造,幸福度,生活満足度,5年後の幸福度
年度,,,,,,,,,,,,,,,,,,,,,
2022,0.00,0.00,0.00,0.00,100.00,100.00,100.00,0.00,100.00,0.00,...,0.00,0.00,0.00,0.00,100.00,100.00,0.00,0.00,0.00,100.00
2023,42.78,42.78,42.78,42.78,42.78,42.78,42.78,42.78,42.78,42.78,...,42.78,42.78,42.78,42.78,42.78,42.78,42.78,42.78,42.78,42.78
2024,55.28,55.28,55.28,55.28,55.28,55.28,55.28,55.28,55.28,55.28,...,55.28,55.28,55.28,55.28,55.28,55.28,55.28,55.28,55.28,55.28
2025,63.34,63.34,63.34,63.34,63.34,63.34,63.34,63.34,63.34,63.34,...,63.34,63.34,63.34,63.34,63.34,63.34,63.34,63.34,63.34,63.34
2026,60.41,60.41,60.41,60.41,60.41,60.41,60.41,60.41,60.41,60.41,...,60.41,60.41,60.41,60.41,60.41,60.41,60.41,60.41,60.41,60.41

In [24]:
for kbn in df_sheet2["区分"].unique():
    print(f"\n{'=' * 60}")
    print(f"■ 区分：{kbn}")
    print(f"{'=' * 60}")

    display(
        missing_by_kbn_year[
            missing_by_kbn_year["区分"] == kbn
        ][["年度", "項目", "欠損数", "欠損率(%)"]]
        .sort_values(["年度", "項目"])
        .reset_index(drop=True)
    )

============================================================
■ 区分：全体
============================================================

       年度         項目   欠損数  欠損率(%)
0    2022    5年後の幸福度  1333  100.00
1    2022  主観_デジタル生活  1333  100.00
2    2022   主観_事故・犯罪     0    0.00
3    2022    主観_事業創造     0    0.00
4    2022    主観_住宅環境     0    0.00
..    ...        ...   ...     ...
130  2026   主観_遊び・娯楽  1155   60.41
131  2026    主観_都市景観  1155   60.41
132  2026   主観_雇用・所得  1155   60.41
133  2026        幸福度  1155   60.41
134  2026      生活満足度  1155   60.41

[135 rows x 4 columns]

============================================================
■ 区分：年代別
============================================================

       年度         項目   欠損数  欠損率(%)
0    2022    5年後の幸福度  6401   100.0
1    2022  主観_デジタル生活  6401   100.0
2    2022   主観_事故・犯罪     0     0.0
3    2022    主観_事業創造     0     0.0
4    2022    主観_住宅環境     0     0.0
..    ...        ...   ...     ...
130  2026   主観_遊び・娯楽     0     0.0
131  2026    主観_都市景観     0     0.0
132  2026   主観_雇用・所得     0     0.0
133  2026        幸福度     0     0.0
134  2026      生活満足度     0     0.0

[135 rows x 4 columns]

============================================================
■ 区分：性別別
============================================================

       年度         項目   欠損数  欠損率(%)
0    2022    5年後の幸福度  2528   100.0
1    2022  主観_デジタル生活  2528   100.0
2    2022   主観_事故・犯罪     0     0.0
3    2022    主観_事業創造     0     0.0
4    2022    主観_住宅環境     0     0.0
..    ...        ...   ...     ...
130  2026   主観_遊び・娯楽     0     0.0
131  2026    主観_都市景観     0     0.0
132  2026   主観_雇用・所得     0     0.0
133  2026        幸福度     0     0.0
134  2026      生活満足度     0     0.0

[135 rows x 4 columns]

============================================================
■ 区分：年代×性別
============================================================

       年度         項目    欠損数  欠損率(%)
0    2022    5年後の幸福度  10096   100.0
1    2022  主観_デジタル生活  10096   100.0
2    2022   主観_事故・犯罪      0     0.0
3    2022    主観_事業創造      0     0.0
4    2022    主観_住宅環境      0     0.0
..    ...        ...    ...     ...
130  2026   主観_遊び・娯楽      0     0.0
131  2026    主観_都市景観      0     0.0
132  2026   主観_雇用・所得      0     0.0
133  2026        幸福度      0     0.0
134  2026      生活満足度      0     0.0

[135 rows x 4 columns]

In [15]:
cols = [
    "主観_遊び・娯楽",
    "主観_子育て",
    "主観_初等・中等教育",
    "主観_デジタル生活",
    "主観_自然の恵み",
    "主観_環境共生",
    "主観_自然災害",
    "主観_教育機会の豊かさ",
    "主観_雇用・所得",
    "5年後の幸福度"
]

# 10項目すべてが欠損している行数
all_missing = df_sheet2[cols].isna().all(axis=1).sum()

# 10項目のどれか1つでも欠損している行数
any_missing = df_sheet2[cols].isna().any(axis=1).sum()

print("10項目すべて欠損:", all_missing)
print("10項目のいずれか欠損:", any_missing)

10項目すべて欠損: 24599
10項目のいずれか欠損: 24599

In [22]:
# 区分 × 年度の行数
year_counts = (
    df_sheet2
    .groupby(["区分", "年度"])
    .size()
    .reset_index(name="行数")
)

# 区分ごとの総行数
total_by_kbn = year_counts.groupby("区分")["行数"].transform("sum")

# 区分内構成比
year_counts["区分内構成比(%)"] = (
    year_counts["行数"] / total_by_kbn * 100
).round(2)

# 並び順を指定
kbn_order = ["全体", "年代別", "性別別", "年代×性別"]
year_counts["区分"] = pd.Categorical(
    year_counts["区分"],
    categories=kbn_order,
    ordered=True
)

year_counts = (
    year_counts
    .sort_values(["区分", "年度"])
    .reset_index(drop=True)
)

display(year_counts)

       区分    年度     行数  区分内構成比(%)
0      全体  2022   1333      14.84
1      全体  2023   1912      21.29
2      全体  2024   1912      21.29
3      全体  2025   1912      21.29
4      全体  2026   1912      21.29
5     年代別  2022   6401      22.89
6     年代別  2023   5683      20.32
7     年代別  2024   5842      20.89
8     年代別  2025   4818      17.23
9     年代別  2026   5225      18.68
10    性別別  2022   2528      23.95
11    性別別  2023   2347      22.23
12    性別別  2024   2080      19.70
13    性別別  2025   1735      16.43
14    性別別  2026   1867      17.68
15  年代×性別  2022  10096      20.83
16  年代×性別  2023   9476      19.55
17  年代×性別  2024  10646      21.97
18  年代×性別  2025   8740      18.04
19  年代×性別  2026   9503      19.61

In [25]:
# 分析対象の項目
target_cols = [
    c for c in df_sheet2.columns
    if c.startswith("主観_")
    or c in ["幸福度", "生活満足度", "5年後の幸福度"]
]

# 区分 × 年度ごとの欠損数・欠損率
missing_counts = []

for (kbn, year), group in df_sheet2.groupby(["区分", "年度"]):
    # 対象項目の欠損セル数
    missing_count = group[target_cols].isna().sum().sum()

    # 対象項目の全セル数
    total_count = group[target_cols].size

    # 欠損率
    missing_rate = missing_count / total_count * 100

    missing_counts.append({
        "区分": kbn,
        "年度": year,
        "欠損数": missing_count,
        "欠損率(%)": round(missing_rate, 2)
    })

missing_by_kbn_year = pd.DataFrame(missing_counts)

# 並び順
kbn_order = ["全体", "年代別", "性別別", "年代×性別"]

missing_by_kbn_year["区分"] = pd.Categorical(
    missing_by_kbn_year["区分"],
    categories=kbn_order,
    ordered=True
)

missing_by_kbn_year = (
    missing_by_kbn_year
    .sort_values(["区分", "年度"])
    .reset_index(drop=True)
)

display(missing_by_kbn_year)

       区分    年度     欠損数  欠損率(%)
0      全体  2022   13330   37.04
1      全体  2023   22086   42.78
2      全体  2024   28539   55.28
3      全体  2025   32697   63.34
4      全体  2026   31185   60.41
5     年代別  2022   64010   37.04
6     年代別  2023       0    0.00
7     年代別  2024       0    0.00
8     年代別  2025       0    0.00
9     年代別  2026       0    0.00
10    性別別  2022   25280   37.04
11    性別別  2023       0    0.00
12    性別別  2024       0    0.00
13    性別別  2025       0    0.00
14    性別別  2026       0    0.00
15  年代×性別  2022  100960   37.04
16  年代×性別  2023       0    0.00
17  年代×性別  2024       0    0.00
18  年代×性別  2025       0    0.00
19  年代×性別  2026       0    0.00

In [26]:
# 全体データ
df_all = df_sheet2[df_sheet2["区分"] == "全体"].copy()

# 年代別データ
df_age = df_sheet2[df_sheet2["区分"] == "年代別"].copy()

# 市×年度の一覧
all_city_year = (
    df_all[["年度", "都道府県", "市区町村"]]
    .drop_duplicates()
)

age_city_year = (
    df_age[["年度", "都道府県", "市区町村"]]
    .drop_duplicates()
)

# 全体にはあるが、年代別には存在しない市×年度
missing_age = all_city_year.merge(
    age_city_year,
    on=["年度", "都道府県", "市区町村"],
    how="left",
    indicator=True
)

missing_age = missing_age[
    missing_age["_merge"] == "left_only"
]

display(
    missing_age.groupby("年度")
    .size()
    .reset_index(name="年代別データが存在しない市数")
)

     年度  年代別データが存在しない市数
0  2023             818
1  2024            1057
2  2025            1211
3  2026            1155